In [61]:
import pandas as pd
from collections import Counter
from pathlib import Path

In [62]:
ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ,.-"
ALLOWED = set(ALPHABET)

def clean_text(text: str) -> str:
    """
    Convert to uppercase and keep only characters
    in the assignment alphabet.
    """
    text = text.upper()
    return "".join(ch for ch in text if ch in ALLOWED)

In [63]:
raw_text = Path("2.txt").read_text(encoding="utf-8", errors="ignore")
ciphertext = clean_text(raw_text)

len(ciphertext)

1130

In [64]:
def one_gram_table(text: str) -> pd.DataFrame:
    counter = Counter(text)
    total = len(text)

    rows = []
    for ch in ALPHABET:
        count = counter.get(ch, 0)
        percent = (count / total) * 100 if total else 0
        rows.append([ch, count, round(percent, 2)])

    df = pd.DataFrame(rows, columns=["Symbol", "Count", "Percentage (%)"])
    return df

one_gram_df = one_gram_table(ciphertext)
one_gram_df

   Symbol  Count  Percentage (%)
0       A    164           14.51
1       B     26            2.30
2       C     13            1.15
3       D     85            7.52
4       E     73            6.46
5       F      1            0.09
6       G      8            0.71
7       H     43            3.81
8       I     29            2.57
9       J     76            6.73
10      K     81            7.17
11      L     16            1.42
12      M      0            0.00
13      N     62            5.49
14      O     76            6.73
15      P     87            7.70
16      Q     30            2.65
17      R      6            0.53
18      S     23            2.04
19      T      3            0.27
20      U     19            1.68
21      V      0            0.00
22      W     27            2.39
23      X      9            0.80
24      Y      4            0.35
25      Z     73            6.46
26      ,     16            1.42
27      .     22            1.95
28      -     58            5.13

In [65]:
def ngram_table(text: str, n: int, top: int) -> pd.DataFrame:
    ngrams = [text[i:i+n] for i in range(len(text) - n + 1)]
    counter = Counter(ngrams)
    total = sum(counter.values())

    rows = []
    for gram, count in counter.most_common(top):
        percent = (count / total) * 100 if total else 0
        rows.append([gram, count, round(percent, 2)])

    df = pd.DataFrame(rows, columns=[f"{n}-gram", "Count", "Percentage (%)"])
    return df

digram_df = ngram_table(ciphertext, n=2, top=16)
digram_df

   2-gram  Count  Percentage (%)
0      DA     51            4.52
1      AN     34            3.01
2      PD     26            2.30
3      EJ     26            2.30
4      A-     22            1.95
5      NA     19            1.68
6      OD     18            1.59
7      ZJ     18            1.59
8      PA     16            1.42
9      J-     16            1.42
10     JP     13            1.15
11     OP     12            1.06
12     AO     12            1.06
13     AJ     11            0.97
14     ZP     11            0.97
15     KQ     11            0.97

In [66]:
trigram_df = ngram_table(ciphertext, n=3, top=11)
trigram_df

   3-gram  Count  Percentage (%)
0     DAN     17            1.51
1     ODA     17            1.51
2     PDA     14            1.24
3     ZJ-     13            1.15
4     ANA     13            1.15
5     DAS      7            0.62
6     WZJ      7            0.62
7     EJC      6            0.53
8     EJP      6            0.53
9     DAH      6            0.53
10    OPA      5            0.44